# Python CircleCI 2.0 cinfiguration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from github
      - checkout
      # Step 2: create virutal env and install dependencies
      - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator